stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy


default:
  cache:
    key:
      files:
        - 'backend/api/package-lock.json'
    paths:
      - 'backend/api/node_modules/'


build-job:       # This job runs in the build stage, which runs first to make nestjs backend runs
  stage: build
  image: node:22-alpine
  script:
    - cd backend/api
    - npm ci
    - npm run build
  artifacts:
    paths:
      - 'backend/api/dist'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


unit-tests-job:   # This job runs in the test stage (unit tests in backend/api/src)
  stage: test   
  image: node:22-alpine
  script:
    - cd backend/api
    - npm ci
    - npm run test
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'


e2e-tests-job:    # runs e2e tests in backend/api/test
  stage: test
  image: node:22-alpine
  script:
    - cd backend/api
    - npm ci
    - npm run test:e2e
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'main'


### frontend -> backend
#smoke-tests:  # runs playwright to run e2e smoke tests (needs docker compose up first)
#  stage: test
#  image: mcr.microsoft.com/playwright:v1.58.2-noble
#  script:
#    - cd backend
#    - npm ci
#    - npx playwright test e2e/smoke
#  rules:
#    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
#    - if: $CI_COMMIT_BRANCH == 'main'


# eslint is allowed to fail but will give warnings
eslint-job:   # This job also runs in the test stage in parallel with e2e testing
  stage: test    
  image: node:22-alpine
  dependencies: []
  script:
    - cd backend/api
    - npm ci
    - npx eslint .
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


deploy-job:      # This job runs in the deploy stage.
  stage: deploy 
  environment: production
  needs: [build-job]
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
