services:
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=1
      - VITE_ALLOWED_HOSTS=${VITE_ALLOWED_HOSTS}

  backend:
    volumes:
      - ./backend/api:/app
      - cache:/app/node_modules
    environment:
      - NODE_ENV=development
      - DEBUG=1